/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2023-03-13 08:33:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1649935150258L));
    _jspx_dependants.put("/WEB-INF/views/include/head.jsp", Long.valueOf(1678696190477L));
    _jspx_dependants.put("/WEB-INF/views/include/plug_in.jsp", Long.valueOf(1660615196000L));
    _jspx_dependants.put("jar:file:/C:/workspaceProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/jiniteamproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("This is a starter template page. Use this page to start your new project from\r\n");
      out.write("scratch. This page gets rid of all links and provides the needed markup only.\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Startup - Startup Website Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Rubik:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.wrap{\r\n");
      out.write("		margin:auto;\r\n");
      out.write("		text-aling:center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.box{\r\n");
      out.write("		vertical-align:middle;\r\n");
      out.write("		display:inline-block;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	header{\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height:100px;\r\n");
      out.write("		padding:1rem;\r\n");
      out.write("		background:teal;\r\n");
      out.write("		font-weight:bold;\r\n");
      out.write("		display:flex;\r\n");
      out.write("		justiy-content:space-between;\r\n");
      out.write("		align-item:center;\r\n");
      out.write("	}	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("<div class=\"header\" id=\"header\">\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark px-5 py-3 py-lg-0\">\r\n");
      out.write("	    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"navbar-brand p-0\">\r\n");
      out.write("	        <h1 class=\"m-0\"><i class=\"fa fa-user-tie me-2\"></i>Startup</h1>\r\n");
      out.write("	    </a>\r\n");
      out.write("	    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("	        <span class=\"fa fa-bars\"></span>\r\n");
      out.write("	    </button>    \r\n");
      out.write("	    <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\" >\r\n");
      out.write("	    	<div class=\"wrap\">\r\n");
      out.write("	    		<div class=\"box\">\r\n");
      out.write("	          <div class=\"navbar-nav ms-auto py-0\">\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"nav-item nav-link active\">홈</a>\r\n");
      out.write("	              <a href=\"about.html\" class=\"nav-item nav-link\">목적지체크</a>\r\n");
      out.write("	              <a href=\"service.html\" class=\"nav-item nav-link\">전체여행지</a>\r\n");
      out.write("	              <div class=\"nav-item dropdown\">\r\n");
      out.write("	                  <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">게시판</a>\r\n");
      out.write("	                  <div class=\"dropdown-menu m-0\">\r\n");
      out.write("	                      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list\" class=\"dropdown-item\">공지사항</a>\r\n");
      out.write("	                      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list\" class=\"dropdown-item\">메인게시판</a>\r\n");
      out.write("	                      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list\" class=\"dropdown-item\">자유게시판</a>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	              </div>\r\n");
      out.write("	      	</div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    	\r\n");
      out.write("	    	\r\n");
      out.write("	<div>\r\n");
      out.write("	    <section class=\"content container-fluid\">\r\n");
      out.write("		    <div class=\"box-header with-border\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</header>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- REQUIRED JS SCRIPTS -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery 3 -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bower_components/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 3.3.7 -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Optionally, you can add Slimscroll and FastClick plugins.\r\n");
      out.write("     Both of these plugins are recommended to enhance the\r\n");
      out.write("     user experience. -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function id_click() {\r\n");
      out.write("	idcheck1.type=\"hidden\";\r\n");
      out.write("	idcheck3.type=\"hidden\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function ename_click(){\r\n");
      out.write("	enamecheck1.type=\"hidden\";\r\n");
      out.write("	enamecheck3.type=\"hidden\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function pass_click() {\r\n");
      out.write("	passcheck.type=\"hidden\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function email_select() {\r\n");
      out.write("	var select = document.getElementById(\"email3\");\r\n");
      out.write("	var selectValue = select.options[select.selectedIndex].value;\r\n");
      out.write("	email2.value = selectValue;\r\n");
      out.write("	if(email2.value == \"\"){\r\n");
      out.write("		$('input[name=email2]').attr('readonly',false);\r\n");
      out.write("	} else {\r\n");
      out.write("		$('input[name=email2]').attr('readonly',true);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	$(\".btn-primary\").click(function(){	\r\n");
      out.write("		var tel1 = document.getElementById(\"tel1\").value;\r\n");
      out.write("		var tel2 = document.getElementById(\"tel2\").value;\r\n");
      out.write("		var tel3 = document.getElementById(\"tel3\").value;\r\n");
      out.write("		$('input[name=m_tel]').attr('value',tel1+\"-\"+tel2+\"-\"+tel3);	\r\n");
      out.write("		var email1 = document.getElementById(\"email1\").value;\r\n");
      out.write("		var email2 = document.getElementById(\"email2\").value;\r\n");
      out.write("		$('input[name=m_email]').attr('value',email1+\"@\"+email2);	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 2-1,2 아이디 중복 확인버튼\r\n");
      out.write("	$(\".btn-idcheck\").click(function(){\r\n");
      out.write("		idcheck1.type=\"hidden\";\r\n");
      out.write("		idcheck2.type=\"hidden\";\r\n");
      out.write("		idcheck3.type=\"hidden\";	\r\n");
      out.write("		var id = document.getElementById(\"m_id\").value;\r\n");
      out.write("		var exptext = /[a-zA-Z0-9/]/;	\r\n");
      out.write("		if(id.length > 7 && id.length < 16){\r\n");
      out.write("			if(exptext.test(id)==false){\r\n");
      out.write("				$('input[name=idcheckNum]').attr('value','2');\r\n");
      out.write("				idcheck3.type=\"text\";\r\n");
      out.write("				document.getElementById(\"m_id\").focus();	\r\n");
      out.write("			} else {\r\n");
      out.write("				$('input[name=idcheckNum]').attr('value','3');\r\n");
      out.write("				idcheck2.type=\"text\";\r\n");
      out.write("			}\r\n");
      out.write("		} else{\r\n");
      out.write("			$('input[name=idcheckNum]').attr('value','2');\r\n");
      out.write("			idcheck3.type=\"text\";\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 2-1, 닉네임 중복 확인버튼\r\n");
      out.write("	$(\".btn-enamecheck\").click(function(){\r\n");
      out.write("		enamecheck1.type=\"hidden\";\r\n");
      out.write("		enamecheck2.type=\"hidden\";\r\n");
      out.write("		enamecheck3.type=\"hidden\";	\r\n");
      out.write("		var ename = document.getElementById(\"m_ename\").value;\r\n");
      out.write("		\r\n");
      out.write("		if(ename.length > 1 && ename.length < 16){\r\n");
      out.write("			$('input[name=enamecheckNum]').attr('value','3');\r\n");
      out.write("			enamecheck2.type=\"text\";\r\n");
      out.write("		} else {\r\n");
      out.write("			enamecheck3.type=\"text\";\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	// 비밀번호 키업\r\n");
      out.write("	$('#m_pw').keyup(function(){\r\n");
      out.write("		$('font[name=passcheck]').text('');\r\n");
      out.write("		if($('#m_pw').val() != $('#password2').val()){\r\n");
      out.write("			$('font[name=passcheck]').text('');\r\n");
      out.write("			$('font[name=passcheck]').html('비밀번호 틀림');\r\n");
      out.write("			$('font[name=passcheck]').attr('color', 'red');\r\n");
      out.write("		} else {\r\n");
      out.write("			$('font[name=passcheck]').text('');\r\n");
      out.write("			$('font[name=passcheck]').html('비밀번호 확인');\r\n");
      out.write("			$('font[name=passcheck]').attr('color', 'green');\r\n");
      out.write("		}\r\n");
      out.write("	});	\r\n");
      out.write("	$('#password2').keyup(function(){\r\n");
      out.write("		if($('#m_pw').val() != $('#password2').val()){\r\n");
      out.write("			$('font[name=passcheck]').text('');\r\n");
      out.write("			$('font[name=passcheck]').html('비밀번호 틀림');\r\n");
      out.write("			$('font[name=passcheck]').attr('color', 'red');\r\n");
      out.write("		} else {\r\n");
      out.write("			$('font[name=passcheck]').text('');\r\n");
      out.write("			$('font[name=passcheck]').html('비밀번호 확인');\r\n");
      out.write("			$('font[name=passcheck]').attr('color', 'green');\r\n");
      out.write("		}	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//유효성 검사\r\n");
      out.write("function validate(){\r\n");
      out.write("	var exptextTel = /^01[016789]+/;\r\n");
      out.write("	var exptextEmail = /^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/;	\r\n");
      out.write("	var id = document.getElementById(\"idcheckNum\").value;\r\n");
      out.write("	var ename = document.getElementById(\"enamecheckNum\").value;\r\n");
      out.write("	\r\n");
      out.write("	var password1 = document.getElementById(\"m_pw\").value;\r\n");
      out.write("	var password2 = document.getElementById(\"password2\").value;\r\n");
      out.write("	\r\n");
      out.write("	var tel = document.getElementById(\"m_tel\").value;\r\n");
      out.write("	var email2 = document.getElementById(\"email2\").value;\r\n");
      out.write("	var email = document.getElementById(\"m_email\").value;\r\n");
      out.write("	\r\n");
      out.write("	if(id != 3){\r\n");
      out.write("		alert(\"아이디 오류\");\r\n");
      out.write("		idcheck1.type=\"text\";\r\n");
      out.write("		document.getElementById(\"m_id\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(ename != 3){\r\n");
      out.write("		alert(\"닉네임 오류\");\r\n");
      out.write("		enamecheck1.type=\"text\";\r\n");
      out.write("		document.getElementById(\"m_ename\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(password1 != password2){\r\n");
      out.write("		alert(\"비밀번호 오류\");\r\n");
      out.write("		passcheck.type=\"text\";\r\n");
      out.write("		document.getElementById(\"m_pw\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(password1 == \"\"){\r\n");
      out.write("		alert(\"비밀번호 오류\");\r\n");
      out.write("		document.getElementById(\"m_pw\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(tel.length < 14 && tel.length >11){\r\n");
      out.write("		if(exptextTel.test(tel)==false){\r\n");
      out.write("			alert(\"전화번호 오류\");\r\n");
      out.write("			document.getElementById(\"tel2\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}	\r\n");
      out.write("	} else{\r\n");
      out.write("		alert(\"전화번호 오류\");\r\n");
      out.write("		document.getElementById(\"tel2\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	if(email2==\"\"){\r\n");
      out.write("		alert(\"이메일 오류\")\r\n");
      out.write("		document.getElementById(\"email1\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	// 2-7 이메일 형식 체크\r\n");
      out.write("	if(exptextEmail.test(email)==false){\r\n");
      out.write("		alert(\"이메일 오류\");\r\n");
      out.write("		document.getElementById(\"email\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	return true;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write(" <div> <br><br>\r\n");
      out.write(" 	<div><h2>회원가입</h2></div><br>\r\n");
      out.write("	<!-- Main content -->\r\n");
      out.write("    <section class=\"content container-fluid\">\r\n");
      out.write("      <form role=\"form\" name=\"f\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("      	<div class=\"box-body\">\r\n");
      out.write("      		<!-- 아이디 -->\r\n");
      out.write("      		<div class=\"box-group\"> \r\n");
      out.write("      			<label>아이디　　　　</label>\r\n");
      out.write("      			<input type='text' id='m_id' name='m_id' onclick=\"id_click();\" minlength=\"8\" maxlength=\"15\" style=\"width:130px\" >\r\n");
      out.write("      			<input type='hidden' id='idcheckNum' name='idcheckNum' value='1'>\r\n");
      out.write("      			<button type=\"button\" class=\"btn btn-idcheck\">중복확인</button>\r\n");
      out.write("      			<input type='hidden' id='idcheck1' name='idcheck1' class=\"form-control\" value=\"중복확인을 하십시오.\" style=\"color:red; width:200px;\">\r\n");
      out.write("      			<input type='hidden' id='idcheck2' name='idcheck2' class=\"form-control\" value=\"중복확인이 완료되었습니다.\" style=\"color:green; width:200px;\" >\r\n");
      out.write("      			<input type='hidden' id='idcheck3' name='idcheck3' class=\"form-control\" value=\"잘못된 아이디 형식입니다.\" style=\"color:red; width:200px;\">		\r\n");
      out.write("      		</div>\r\n");
      out.write("      	\r\n");
      out.write("      		<!-- 비밀번호 --><br>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<label>비밀번호　　　</label>\r\n");
      out.write("      			<input type='password' id='m_pw' name='m_pw' onclick=\"pass_click();\">\r\n");
      out.write("      		</div>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<br><label>비밀번호확인　</label>\r\n");
      out.write("      			<input type='password' id='password2' name='password2' onclick=\"pass_click();\">\r\n");
      out.write("      			<font name=\"passcheck\" size=\"2\"></font>\r\n");
      out.write("      		</div>\r\n");
      out.write("\r\n");
      out.write("      		<!-- 닉네임 -->\r\n");
      out.write("      		<br><div class=\"box-group\">\r\n");
      out.write("      			<label>닉네임　　　　</label>\r\n");
      out.write("      			<input type='text' id='m_ename' name='m_ename' onclick=\"ename_click();\" maxlength=\"15\" style=\"width:130px\" >\r\n");
      out.write("      			<input type='hidden' id='enamecheckNum' name='enamecheckNum' value='1'>\r\n");
      out.write("      			<button type=\"button\" class=\"btn btn-enamecheck\">중복확인</button>\r\n");
      out.write("      			<input type='hidden' id='enamecheck1' name='enamecheck1' class=\"form-control\" value=\"중복확인을 하십시오.\" style=\"color:red; width:200px;\">\r\n");
      out.write("      			<input type='hidden' id='enamecheck2' name='enamecheck2' class=\"form-control\" value=\"중복확인이 완료되었습니다.\" style=\"color:green; width:200px;\" >\r\n");
      out.write("      			<input type='hidden' id='enamecheck3' name='enamecheck3' class=\"form-control\" value=\"잘못된 아이디 형식입니다.\" style=\"color:red; width:200px;\">		\r\n");
      out.write("      		</div>\r\n");
      out.write("      		      		\r\n");
      out.write("      		<!-- 이름 --><br>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<label>이름　　　　　</label>\r\n");
      out.write("      			<input type='text' id='m_name' name='m_name' onclick=\"name_click();\" style=\"width:130px\">\r\n");
      out.write("      		</div>\r\n");
      out.write("      		\r\n");
      out.write("      		<!-- 핸드폰번호 --><br>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<label>핸드폰번호　　</label>\r\n");
      out.write("      			<select id='tel1' name='tel1' style=\"width:70px; height:32;\">\r\n");
      out.write("      				<option value=\"010\">010</option>\r\n");
      out.write("      				<option value=\"011\">011</option>\r\n");
      out.write("      				<option value=\"016\">016</option>\r\n");
      out.write("      				<option value=\"017\">017</option>\r\n");
      out.write("      				<option value=\"019\">019</option>\r\n");
      out.write("      			</select> - \r\n");
      out.write("      			<input type='text' id='tel2' name='tel2' minlength=\"3\" maxlength=\"4\" style=\"width:70px; height:28;\"> - \r\n");
      out.write("      			<input type='text' id='tel3' name='tel3' minlength=\"4\" maxlength=\"4\" style=\"width:70px; height:28;\">\r\n");
      out.write("      			<input type='hidden' id='m_tel' name='m_tel'>\r\n");
      out.write("      		</div>\r\n");
      out.write("      		<!-- 생년월일 --><br>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<label>주민등록번호　</label>\r\n");
      out.write("      			<input type=\"text\" id=\"m_birth\" name=\"m_birth\" minlength=\"6\" maxlength=\"6\" style=\"width:150px; height:28;\"> - \r\n");
      out.write("      			<input type=\"text\" id=\"m_gender\" name=\"m_gender\" minlength=\"1\" maxlength=\"1\" style=\"width:30px; height:28;\">******\r\n");
      out.write("      		</div>\r\n");
      out.write("      		<!-- 이메일 --><br>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<label>이메일　　　　</label>\r\n");
      out.write("      			<input type=\"text\" id=\"email1\" name=\"email1\" style=\"width:120px; height:32;\"> @ \r\n");
      out.write("      			<input type=\"text\" id=\"email2\" name=\"email2\" style=\"width:120px; height:32;\">\r\n");
      out.write("      			<select id='email3' name='email3' onchange=\"email_select();\" style=\"width:120px; height:32;\">\r\n");
      out.write("      				<option value=\"\">직접입력</option>\r\n");
      out.write("      				<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("      				<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("      				<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("      			</select>\r\n");
      out.write("      			<input type=\"hidden\" id=\"m_email\" name=\"m_email\"> \r\n");
      out.write("      		</div>\r\n");
      out.write("      		\r\n");
      out.write("      		<!-- 개인정보 공유에 대한 약관 --><br>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<label>개인정보 약관 동의(필수)</label><br>\r\n");
      out.write("      			<textarea id=\"info\" name=\"info\" rows=\"3\" style=\"width:350px\" value=\"안녕하세요\" readonly></textarea>\r\n");
      out.write("      			<br><input type=\"radio\" id=\"m_info_yn\" name=\"m_info_yn\" value=\"1\" checked=\"checked\">동의　\r\n");
      out.write("      			<input type=\"radio\" id=\"m_info_yn\" name=\"m_info_yn\" value=\"2\">거부\r\n");
      out.write("      		</div>\r\n");
      out.write("      		<!-- 광고 수신 여부에 대한 약관(선택) --><br>\r\n");
      out.write("      		<div class=\"box-group\">\r\n");
      out.write("      			<label>광고수신 약관 동의(선택)</label><br>\r\n");
      out.write("      			<textarea id=\"adv\" name=\"adv\" rows=\"3\" style=\"width:350px\" value=\"안녕하세요\" readonly></textarea>\r\n");
      out.write("      			<br><input type=\"radio\" id=\"m_adv_yn\" name=\"m_adv_yn\" value=\"1\" checked=\"checked\">동의　\r\n");
      out.write("      			<input type=\"radio\" id=\"m_adv_yn\" name=\"m_adv_yn\" value=\"2\">거부\r\n");
      out.write("      		</div>\r\n");
      out.write("      		<div class=\"box-footer\"><br>\r\n");
      out.write("      			<button type=\"submit\" class=\"btn btn-primary\">확인</button>\r\n");
      out.write("      			<button type=\"button\" class=\"btn btn-primary\">취소</button>\r\n");
      out.write("      		</div>\r\n");
      out.write("      	</div>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/join.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/join.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/join.jsp(4,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/include/head.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("contextPath");
      // /WEB-INF/views/include/head.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/head.jsp(4,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/include/head.jsp(98,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<h4><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/login\"><i class=\"fa fa-link\"></i> <span>로그인</span></a></h4>\r\n");
          out.write("				<h6><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/join\"><i class=\"fa fa-link\"></i> <span>회원가입</span></a></h6>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/include/head.jsp(102,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다. <br />\r\n");
          out.write("				\r\n");
          out.write("				<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/logOut\"><i class=\"fa fa-link\"></i> <span>로그아웃</span></a></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
